project:
  type: website
  output-dir: _site
  execute-dir: project
  render:
    - index.qmd
    - qmd/introduction.qmd
    - qmd/methods.qmd
    - qmd/participants.qmd
    - qmd/question1.qmd
    - qmd/question2.qmd
    - qmd/question3.qmd
    - qmd/question4.qmd
    - qmd/discussion.qmd
    - qmd/supplementary.qmd

website:
  title: "In God We Trust, In AI We Ask"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: qmd/introduction.qmd
        text: Introduction
      - href: qmd/methods.qmd
        text: Methods
      - href: qmd/participants.qmd
        text: Participants
      - href: qmd/question1.qmd
        text: "Question 1 — Does Self-Reported Religiosity Predict Frequency of Seeking Moral Advice from AI Chatbots?"
      - href: qmd/question2.qmd
        text: "Question 2 — Does Behavioral Religiosity Predict Frequency of Seeking Moral Advice from AI Chatbots?"
      - href: qmd/question3.qmd
        text: "Question 3 — What Explains the Relationship Between Religiosity and the Frequency of Seeking Moral Advice from AI Chatbots? (Exploratory Indirect Associations)"
      - href: qmd/question4.qmd
        text: "Question 4 — Does Access to Sources of Moral Advice Moderate the Relationship between Religiosity and Seeking Moral Advice from AI Chatbots?"
      - href: qmd/discussion.qmd
        text: Discussion
      - href: qmd/supplementary.qmd
        text: Supplementary

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    number-sections: true
    number-offset: 1
    embed-resources: true
    css: styles.css

execute:
  freeze: auto
  cache: false

knitr:
  opts_chunk:
    fig.path: "_build/figures/"

bibliography: references.bib
