project:
  type: manuscript
  execute-dir: project

manuscript:
  article: manuscript.qmd

format:
  apaquarto-docx:
    toc: false

execute:
  freeze: auto
  cache: true

bibliography: references.bib
fontsize: 12pt
